global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'quiz-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['quiz-service:8080']

  - job_name: 'session-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['session-service:8080']

  - job_name: 'websocket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['websocket-service:8080']

  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-service:8080']
